//class for creating walls of the maze
class Walls{
    constructor(){
      //creating the walls
      for(var i = 20;i<400;i = i+40){
        for(var j = 40;j<600;j = j+40){
          var wallV = createSprite(j,i,5,40);
          wallV.shapeColor = "#EEEEEE";
          wallV.visible = false;
          wallsGroup.add(wallV);
          wallsV.push(wallV);
        }
      }
      for(var i = 20;i<600;i = i+40){
        for(var j = 40;j<400;j = j+40){
          var wallH = createSprite(i,j,40,5);
          wallH.shapeColor = "#EEEEEE";
          wallH.visible = false;
          wallsGroup.add(wallH);
          wallsH.push(wallH);
        }
      }
    }
  
    //functions for removing the walls of the maze
    removeWallsV(){
      wallsV[1].destroy();
      wallsV[2].destroy();
      wallsV[3].destroy();
      wallsV[4].destroy();
      wallsV[6].destroy();
      wallsV[7].destroy();
      wallsV[14].destroy();
      wallsV[15].destroy();
      wallsV[16].destroy();
      wallsV[44].destroy();
      wallsV[46].destroy();
      wallsV[29].destroy();
      wallsV[42].destroy();
      wallsV[126].destroy();
      wallsV[127].destroy();
      wallsV[57].destroy();
      wallsV[86].destroy();
      wallsV[59].destroy();
      wallsV[101].destroy();
      wallsV[129].destroy();
      wallsV[130].destroy();
      wallsV[33].destroy();
      wallsV[21].destroy();
      wallsV[48].destroy();
      wallsV[132].destroy();
      wallsV[133].destroy();
      wallsV[134].destroy();
      wallsV[135].destroy();
      wallsV[136].destroy();
      wallsV[137].destroy();
      wallsV[138].destroy();
      wallsV[105].destroy();
      wallsV[106].destroy();
      wallsV[108].destroy();
      wallsV[109].destroy();
      wallsV[110].destroy();
      wallsV[119].destroy();
      wallsV[120].destroy();
      wallsV[121].destroy();
      wallsV[122].destroy();
      wallsV[123].destroy();
      wallsV[91].destroy();
      wallsV[92].destroy();
      wallsV[63].destroy();
      wallsV[64].destroy();
      wallsV[78].destroy();
      wallsV[50].destroy();
      wallsV[36].destroy();
      wallsV[23].destroy();
      wallsV[37].destroy();
      wallsV[10].destroy();
      wallsV[11].destroy();
      wallsV[12].destroy();
      wallsV[13].destroy();
      wallsV[9].destroy();
      wallsV[41].destroy();
      wallsV[25].destroy();
      wallsV[26].destroy();
      wallsV[52].destroy();
      wallsV[66].destroy();
      wallsV[67].destroy();
      wallsV[54].destroy();
      wallsV[55].destroy();
      wallsV[79].destroy();
      wallsV[80].destroy();
      wallsV[81].destroy();
      wallsV[82].destroy();
      wallsV[83].destroy();
      wallsV[69].destroy();
      wallsV[94].destroy();
      wallsV[95].destroy();
      wallsV[96].destroy();
      wallsV[97].destroy();
    }
    removeWallsH(){
      wallsH[0].destroy();
      wallsH[1].destroy();
      wallsH[28].destroy();
      wallsH[29].destroy();
      wallsH[20].destroy();
      wallsH[11].destroy();
      wallsH[3].destroy();
      wallsH[4].destroy();
      wallsH[5].destroy();
      wallsH[6].destroy();
      wallsH[7].destroy();
      wallsH[8].destroy();
      wallsH[13].destroy();
      wallsH[14].destroy();
      wallsH[15].destroy();
      wallsH[16].destroy();
      wallsH[22].destroy();
      wallsH[23].destroy();
      wallsH[24].destroy();
      wallsH[25].destroy();
      wallsH[26].destroy();
      wallsH[32].destroy();
      wallsH[31].destroy();
      wallsH[40].destroy();
      wallsH[41].destroy();
      wallsH[42].destroy();
      wallsH[35].destroy();
      wallsH[34].destroy();
      wallsH[44].destroy();
      wallsH[52].destroy();
      wallsH[53].destroy();
      wallsH[51].destroy();
      wallsH[50].destroy();
      wallsH[49].destroy();
      wallsH[48].destroy();
      wallsH[36].destroy();
      wallsH[37].destroy();
      wallsH[38].destroy();
      wallsH[45].destroy();
      wallsH[46].destroy();
      wallsH[54].destroy();
      wallsH[55].destroy();
      wallsH[72].destroy();
      wallsH[64].destroy();
      wallsH[65].destroy();
      wallsH[57].destroy();
      wallsH[58].destroy();
      wallsH[59].destroy();
      wallsH[60].destroy();
      wallsH[61].destroy();
      wallsH[62].destroy();
      wallsH[125].destroy();
      wallsH[124].destroy();
      wallsH[97].destroy();
      wallsH[70].destroy();
      wallsH[87].destroy();
      wallsH[67].destroy();
      wallsH[68].destroy();
      wallsH[74].destroy();
      wallsH[84].destroy();
      wallsH[91].destroy();
      wallsH[81].destroy();
      wallsH[126].destroy();
      wallsH[127].destroy();
      wallsH[118].destroy();
      wallsH[100].destroy();
      wallsH[101].destroy();
      wallsH[93].destroy();
      wallsH[110].destroy();
      wallsH[111].destroy();
      wallsH[130].destroy();
      wallsH[129].destroy();
      wallsH[95].destroy();
      wallsH[132].destroy();
      wallsH[133].destroy();
      wallsH[134].destroy();
    }
  }